//LOADING
export const LOADING_BEGIN = "LOADING_BEGIN"
export const LOADING_END = "LOADING_END"
//MOVIES
export const MOVIES_POPULAR = "MOVIE_POPULAR"
export const MOVIES_TOP_RATED = "MOVIE_TOP_RATED"
export const MOVIES_NEW_IN = "MOVIE_NEW_IN"
//TV_SHOWS
export const TV_SHOWS_POPULAR = "TV_SHOW_POPULAR"
export const TV_SHOWS_TOP_RATED = "TV_SHOW_TOP_RATED"
//CINEMA
export const IN_THEATERS = "IN_THEATERS"
//GENRES
export const GENRES = "GENRES"
export const MOVIES_GENRE = "MOVIES_GENRE"
//MOVIE DETAIL
export const MOVIE_DETAIL = "MOVIE_DETAIL"
//SEARCH MOVIE
export const MOVIE_SEARCH = "MOVIE_SEARCH"
